name: Deployment

on:
  push:
    branches: [ _main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: npm

      - name: Install dependencies
        env:
          ACF_PRO_KEY: ${{ secrets.ACF_PRO_KEY }}
          WP_PLUGIN_GF_KEY: ${{ secrets.WP_PLUGIN_GF_KEY }}
        run: |
          npm install
          composer install --no-dev

      - name: Build
        run: npm run build

      - name: Sync
        env:
          dest: 'user@host:destination'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -avh \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /.htaccess \
            --exclude /.env \
            --exclude /web/.htaccess \
            --exclude /web/app/uploads/**/* \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
